# input data config
data_file: data_std.txt
rescale: std
num_channels: 5
data_format_py3:
  - [timestamp, U13]
  - [CROND, f8]
  - [RSYSLOGD, f8]
  - [SESSION, f8]
  - [SSHD, f8]
  - [SU, f8]
data_format_py2:
  - [timestamp, S13]
  - [CROND, f8]
  - [RSYSLOGD, f8]
  - [SESSION, f8]
  - [SSHD, f8]
  - [SU, f8]
headlines: 1
training_data_range_limit: [0, 3000]  # no limit by assigning it to [-1,-1]
test_data_range_limit: [3000, 3457]  # no limit by assigning it to [-1,-1]
# slotting config
slot_size: 3  # disable slotting by assigning slot_size to -1
# model parameters
model_name: One Class SVM
SVMKernel: rbf
gamma: scale
contamination: 0.1
decision_save_path: train_result_OCSVM.txt
model_save_path: saved_model.mdl
