# input data config
data_file: data_std.txt
rescale: std
num_channels: 5
data_format_py3:
  - [timestamp, U13]
  - [CROND, f8]
  - [RSYSLOGD, f8]
  - [SESSION, f8]
  - [SSHD, f8]
  - [SU, f8]
data_format_py2:
  - [timestamp, S13]
  - [CROND, f8]
  - [RSYSLOGD, f8]
  - [SESSION, f8]
  - [SSHD, f8]
  - [SU, f8]
headlines: 1
training_data_range_limit: [-1, -1]  # no limit by assigning it to [-1,-1]
test_data_range_limit: [-1, -1]  # no limit by assigning it to [-1,-1]
# slotting config
slot_size: 3  # disable slotting by assigning slot_size to -1
# model parameters
model_name: Isolation Forest
trees: 100
samples_tree: 256 # 'auto'
features_tree: 1
cr: 0.1 # contamination rate
decision_save_path: train_result_isoForest.txt
model_save_path: saved_model.mdl
